[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.15.1"

[[redirects]]
  from = "/callback"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "nuxt"